### ISSUE TITLE
Excluding values outside a range

### ISSUE THREAD

**Issue by Quaxo76** [Limych/ha-average#120]
**Is your feature request related to a problem? Please describe.**

I'm using this sensor, to show a running average for the COP (efficiency) of my domestic heat pump, for the last 24 hours. It works, but there is a problem: when the pump does its automatic de-frosting cycles, the COP becomes negative; and when the pump is off (not needed) the COP is zero. And when the pump is off but the circolator is on, the leftover heat from the radiators is seen as a huge (unrealistic) efficiency. All these zero and negative values, and the too-high ones, strongly affect the average of the normal-use values.

**Describe the solution you'd like**

A good solution would be to only include, in the average, sensor values that fall in a specified range. In my case, I would declare i.e. min=1 and max=6, and only COP values between 1 and 6 would be used.

**Describe alternatives you've considered**

The only alternative I can think of, would be to exclude the out-of-range values directly in the COP definition in Home Assistant. But this way, those values wouldn't be shown at all. I like them to be shown in the instant graph, I just want them not to be considered in the average.

**Additional context**

**Comment by Limych** [comment]
Data filtering is not a function of this sensor.  

You can filter source data using an intermediate template sensor.  The Average sensor by default ignores all undefined values.
