### ISSUE TITLE
Enable START and END to not require 2 variables

### ISSUE THREAD

**Issue by townsmcp** [Limych/ha-average#13]
Request

I would like to be able to call just 1 variable of either Start or Stop.  
My usable of Average works out the average lux of 2 or more motion/lux sensors (Philips Hue sensors).
My current automation takes the average lux and, depending on the value, will turn lights on. 
The problem is, when lights go on, the lux average goes up. Hue sensors capture lux every 5 minutes or when there is motion (however when there is motion after a high lux, a race condition occurs and the new average lux remains high due to both motion sensors needing to gather new lux data - generally, 1 of the sensors will show low lux (beta season movement triggered a lux update request), however as the 2nd Sensor hasn’t been activated to take a new reading, its value is still high and therefore average lux is too high and no lights come on)

**_Scenario 1_** - Working well
Sensor 1 value is 3 lux.
Sensor 2 value is 3 lux.
Last motion was 10 minutes ago.
Average lux has the correct low value (eg 3).
When there is motion, automation checks average lux, which is below threshold, and turns on the light.
Average lux value goes to 90 (due to sensor 1 and 2 having average lux of 90).

**_Scenarios 2_** - Not working as expected
Scenario 1 has been executed.
Lights turn off.
Average lux is 90.
Within 1 minute, motion sensors detect new motion.
Sensor 1 value is 3 (due to lights off and motion triggered a new lux reading).
Sensor 2 value is 90 (due to no new lux sensor update and the 5 minute trigger for a new reading hasn’t been reached).
Average lux value changes due to 1 motion sensor lux reading at 3 (due to new motion). But sensor 2 lux value hasn’t changed and so is still 90. 
Average lux value is 46.5.
Automation evaluates average lux value but doesn’t turn on the lights.

To be able to call average sensor update with a Start or Stop.
Start would begin recording new sensor values.
Stop would stop recording sensor values.
Or some other way to be able to start and stop recording average values

**Comment by Limych** [comment]
Create in HA one (only for start) or two (for start and stop) auxiliary input_datetime, where you write the current time through automation.  And use these values ​​in the average sensor by analogy with how the templates are used in the examples:

https://github.com/Limych/ha-average/blob/master/README.md#examples

Here is an example of how this is done:

https://amp.reddit.com/r/homeassistant/comments/elybp8/tutorial_make_your_dryer_washing_machine_smart/
