### ISSUE TITLE
Average sensor records lot of unnecessary attribute in the recorder that fills up the database quite fast.

### ISSUE THREAD

**Issue by lmagyar** [Limych/ha-average#132]
**Environment**

- Home Assistant Core release with the issue: 2022.5.0+
- This custom component release with the issue: 2.2.1
- Last working this custom component release (if known): -
- Operating environment (Home Assistant/Supervisor/Docker/venv): OS

**Describe the bug**

Average sensor records lot of unnecessary attribute in the recorder that fills up the database quite fast.

Based on https://github.com/home-assistant/core/pull/70154/files I've tried to add a function to exclude these attributes, but had no effect, sure my HA/Python knowledge is ineligible:
```
@callback
def exclude_attributes(hass: HomeAssistant) -> set[str]:
    """Exclude some attributes from being recorded in the database."""
    attributes_to_exclude = set(ATTR_TO_PROPERTY)
    attributes_to_exclude.discard(ATTR_SOURCES)
    return attributes_to_exclude
```

**Configuration.yaml**

**Steps to Reproduce**

**Expected behavior**

Recorded attributes should be shortened from this: `{"state_class":"measurement","start":"2022-05-06T22:21:11+02:00","end":"2022-05-06T22:22:11+02:00","sources":["sensor.working_room_temperature"],"count_sources":1,"available_sources":1,"count":9,"max_value":23.4,"min_value":23.4,"device_class":"temperature","friendly_name":"Working room Temperature Average","icon":"hass:thermometer"}`

To this: `{"state_class":"measurement","sources":["sensor.working_room_temperature"],"unit_of_measurement":"\u00b0C","device_class":"temperature","friendly_name":"Working room Temperature Average","icon":"hass:thermometer"}`

_**These are constant values and recorded only once in the recorder database in the state_attributes table!**_

**Debug log**

**Additional context**

**Comment by Limych** [comment]
Thank you :heart:

**Comment by lmagyar** [comment]
I think this issue should be reopened.

I've upgraded to the latest v2.3.0, restart, and it still records the same non-constant attributes: `{"state_class":"measurement","start":"2022-08-03T02:49:48+02:00","end":"2022-08-03T02:50:48+02:00","sources":["sensor.spare_humidity"],"count_sources":1,"available_sources":1,"count":8,"max_value":60.6,"min_value":60.4,"unit_of_measurement":"%","device_class":"humidity","friendly_name":"Spare humidity average","icon":"hass:water-percent"}`

Strange.

**Comment by lmagyar** [comment]
It seems, we had to wait for core 2023.3.0, because previous core versions weren't aware of these attribute exclude lists in case of integrations (if I understand correctly this core issue [88357](https://github.com/home-assistant/core/pull/88357)).

After core 2023.3.0 this integration works exactly as expected above, ie. storing a constant attribute list.
