### ISSUE TITLE
Option for adding more attributes

### ISSUE THREAD

**Issue by ACrazyConcept** [Limych/ha-average#14]
I have just installed this and I quite like it.

I am currently using both template sensors and min_max sensors. But neither are really good solutions I think.
The min_max sensor creates spikes when one of the source sensors goes unknown: 
![image](https://user-images.githubusercontent.com/36438756/87220211-40d2f580-c362-11ea-9b40-9b7231596a1f.png)
And the template sensor requires to write a lot of code if you want to add the slightes bit of complexity/additional info.

So this looks better since it seems to create gaps if any source values are missing instead of spikes, which I prefer: 
![image](https://user-images.githubusercontent.com/36438756/87220305-edad7280-c362-11ea-92ef-99f30be04883.png)

And when adding the time duration average (I assume the math is essentially the same as the time_simple_moving_average in the filter sensor) in the same sensor, a couple of intermidiate sensors are no longer needed.

But was wondering if the following additional features would be possible to add without too much work:

Option to add the source sensors as sensor attributes would be cool. Something like this: 
![image](https://user-images.githubusercontent.com/36438756/87220439-01a5a400-c364-11ea-8f51-ec1c5a657f13.png)

It could also be interesting to add the time since last_update of the source sensor which was updated the longest time ago.

**Comment by Limych** [comment]
It is difficult to give a complete list of the states of the source sensors. It is still possible for the average of current states. But for the average of historical states, there will be hundreds of values ​​that will overload your database when HA try to save this average sensor state to history. But by default, this saving is enabled for everyone.

In commit https://github.com/Limych/ha-average/commit/0c0bfc508273dce26cb6d60b4c361330e6f30e56 (not yet published to master) I added an attribute that lists the full list of source sensors. Using this list, you can get the data you need on their states.

I think this decision will suit you.
