### ISSUE TITLE
Possible Service Call To Reset An Average?

### ISSUE THREAD

**Issue by somejavadev** [Limych/ha-average#150]
**Is your feature request related to a problem? Please describe.**

Yes, I had to re-calibrate some sensors involved in averages which are kept for a long period of time eg. a couple of months or year, I can't seem to find any information on how the reset the average.

**Describe the solution you'd like**

Perhaps a service call to reset the average for a specific average sensor.

**Describe alternatives you've considered**

Recreating the sensor is possible but this is quite frustrating to go and rename the sensor for all the integrations it is already used in.

**Additional context**

**Comment by Limych** [comment]
This sensor does not store any information.  Each time for each time point, the calculation is performed on all participating data.

So there is no way to make a sensor's "reset" service, sorry — after such an operation the result will not change.
