### ISSUE TITLE
Configuration items

### ISSUE THREAD

**Issue by Eckart0** [Limych/ha-average#151]
hi,
is it possible to implement the following items to the config options, here with examples:

      icon: "mdi:thermometer"
      icon_template: {% ... %}
      unit_of_measurement: "°C"
      device_class: temperature

Regards, Eckart

**Comment by Limych** [comment]
Icon customization is not related to the logic of the sensor.  You can always do it through the default entity customization option: https://www.home-assistant.io/docs/configuration/customizing-devices/

Units of measurement and sensor class are automatically set from similar fields of the first source sensor.  If something does not work correctly, look there first.

So, sorry, but your whole issue does not make sense and I close it.  _(Moreover, in the description of the template for the issue that you deigned to ignore, it is clearly written that ignoring the template by you is equal to ignoring the issue by me)_
