### ISSUE TITLE
Data from the current month only

### ISSUE THREAD

**Issue by Takst3in** [Limych/ha-average#154]
Hi,

Thanks for the examples given in the configuration, however, I am not able to figure out how to configure the sensor to only show average-data from within the current month, ie; (today is 15.August) I would like the data from 01. August 00:00:00 to "now".

Please explain, Thanks!

**Comment by Limych** [comment]
```yaml
start: '{{ now().replace(day=1).replace(hour=0).replace(minute=0).replace(second=0) }}'
end: '{{ now() }}'
```
