### ISSUE TITLE
Issue with sensors not reporting continuously

### ISSUE THREAD

**Issue by hossians** [Limych/ha-average#17]
Hi

I have an issue with sensors that only report data when there is a change. I'm using the built in filter sensor that produce wrong data when no more data is coming in, i.e. when the sun goes down and no more sun kw is reported it still shows the last calculated average. I was hoping your sensor would solve my issue as you took into account the time you have had a value. But I get a new issue with large jumps in readings instead, likely also caused by the sensor not reporting any value for some time. 

The red curve is the filter sensor (moving average, window 30min) and the other colour is the average sensor (duration 30min). Is this something that can be solved?

![bild](https://user-images.githubusercontent.com/44232102/92314043-bd84f780-efd2-11ea-8d88-f2ec31e0c57f.png)

/Henrik

**Comment by Limych** [comment]
Please test the latest version of the component (1.4.4) that was published today. There added the data availability attribute. Perhaps this will help in solving your problem.

**Comment by hossians** [comment]
Hi
Thanks for your reply. The update didn't help. This is sensors that just do not report anything when there is nothing new to report. Especially value 0 seems to be an issue. Here is a new graph, this time the green is the average sensor and the purple is the unfiltered signal. 
![bild](https://user-images.githubusercontent.com/44232102/92361979-8fe1a080-f0ef-11ea-9bb2-b78e34d9bf5f.png)

As you can see it goes from 0 to -1kW and the average sensor more or less directly reacts to that instead of smoothing it out. When the raw signal again jumps back to 0 this it not seen by the sensor and the average stays on a large negative value. 

Thanks for looking in to it. 

/Henrik

**Comment by Limych** [comment]
Thank you for paying attention to this situation.  Yes, this is a bug.  And very nasty.  It consists in the fact that the average sensor ignores zero values ​​at the beginning of the calculated period.  I already know how to fix it, but you'll have to wait until I get to my main computer.

**Comment by hossians** [comment]
No problem to wait, thank you for your support! 

/Henrik
