### ISSUE TITLE
Frequency of sensor update

### ISSUE THREAD

**Issue by miguelmartfern** [Limych/ha-average#186]
I have this sensor in my config:

```
  - platform: average
    name: temp_media
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    entities: sensor.pws_temp
```

If I make next query at the database:
```
SELECT entity_id, COUNT(*) as count
FROM "states" where entity_id = "sensor.pws_temp"  or entity_id = "sensor.temp_media" group by entity_id order by count desc
```

I get much more states for the average sensor than from the original one:

```
sensor.temp_media | 41453
sensor.pws_temp | 743
```
If I look in more detail in the database, I see that the average sensor is updated every 30s, much faster than the source sensor.

Is there a way to set/limit the update frequency of the sensor?

**Comment by Limych** [comment]
https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval

**Comment by miguelmartfern** [comment]
Thanks!

**Comment by TheBazeman** [comment]
So I have noticed this also. When you are using trigger on state change of the average sensor in an automation: the automation gets a trigger every 30s while the value for the average sensor is exactly the same for minutes or even hours.

The average sensor is exactly what I was looking for but this behaviour is unwanted for me. Is there something to do about it? scan_interval is not the solution for false triggering automations, I just want it to trigger when the actual value is changing.

Thanks in advance,
Bas

**Comment by ddaddy** [comment]
Did you manage to get the `scan_interval` working?

I tried adding this to my config but it still only updates every 30 seconds.
```yml
average:
  scan_interval: 5
```
