### ISSUE TITLE
This integration will stop working with Home Assistant 2023.4

### ISSUE THREAD

**Issue by jwfox5150** [Limych/ha-average#189]
Temperature utility is deprecated, need to use unit_conversion.TemperatureConverter.

`[homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for average using this method at custom_components/average/sensor.py, line 258: temperature = convert_temperature(float(temperature), entity_unit, ha_unit)`

**Comment by jwfox5150** [comment]
It looks like this has already been addressed, just needs to be pushed to a release.

**Comment by Salamandar** [comment]
@Limych 2023.04 is out and this is not fixed :'(

**Comment by jwfox5150** [comment]
@Salamandar, I recommend you do what I did and remove this custom integration and move over any average sensors to a "Helper" sensor, native to Home Assistant.

**Comment by Salamandar** [comment]
> @Salamandar, I recommend you do what I did and remove this custom integration and move over any average sensors to a "Helper" sensor, native to Home Assistant.

There is no helper doing the same "smoothing" job, unfortunately.

**Comment by thecem** [comment]
@jwfox5150 could you show us your config for an average sensor?

**Comment by Joao-Sousa-71** [comment]
> @jwfox5150 could you show us your config for an average sensor?

I have the same chalenge like as the @jwfox5150 here is a sample of my sensors:

`sensor:
  - platform: average
    name: irrigation_unlimited_rain_0
    unique_id: irrigation_unlimited_rain_0
    entities:
      - sensor.pws_precip_total
    precision: 1
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) }}"
    end: "{{ now() }}"
    scan_interval: 600`

**Comment by creeve4** [comment]
@Limych any plans to continue supporting this integration?

**Comment by gieljnssns** [comment]
If you wan't to use the latest commits, you have to redownload the integration via HACS and the choose the dev version
<img width="518" alt="Scherm­afbeelding 2023-08-07 om 03 43 05" src="https://github.com/Limych/ha-average/assets/17234951/35d3228a-fd2f-4de4-8d9c-111462a98466">
