### ISSUE TITLE
Ignore unavailable

### ISSUE THREAD

**Issue by mf-social** [Limych/ha-average#2]
**Is your feature request related to a problem? Please describe.**

Yes, if one of the entities goes unavailable, the sensor output is 'unknown' 

**Describe the solution you'd like**

If I have 5 sensors and one goes offline, ignore the offline one and give me the average reading of the remaining 4.

**Describe alternatives you've considered**

Using a template sensor ignores the unavailable entity, but of course treats it as zero, which skews the average for the remaining sensors.

**Comment by Limych** [comment]
Does the sensor write anything to the logs when one of the sources is unavailable? I would like to see the logs. This will greatly accelerate the work.

**Comment by alwashe** [comment]
this would be great, like in the min_max platform, if the state of sensors are unknown pls ignore them.

Now: if one sensors state is unknown the average value is also unknown.

**Comment by mf-social** [comment]
@Limych

```
2019-09-23 10:15:19 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.test_avg_temp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 439, in async_device_update
    await self.async_update()
  File "/config/custom_components/average/sensor.py", line 212, in async_update
    'Unable to find an entity called {}'.format(entity_id))
homeassistant.exceptions.HomeAssistantError: Unable to find an entity called sensor.bathroom_temperature
```

**Comment by Limych** [comment]
Please test this version of sensor:
https://github.com/Limych/ha-average/blob/d50ec1da99f31c700b248fe6119021806bd7f23e/custom_components/average/sensor.py
