### ISSUE TITLE
Deprecated constants warnings in 2024.1

### ISSUE THREAD

**Issue by gionaf** [Limych/ha-average#214]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Since 2024.1 i get these logs:

STATE_CLASS_MEASUREMENT was used from average, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/Limych/ha-average/issues

DEVICE_CLASS_TEMPERATURE was used from average, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please create a bug report at https://github.com/Limych/ha-average/issues

### Describe the solution you'd like

I think you should use SensorDeviceClass and SensorStateClass

### Describe alternatives you've considered

none

### Additional context

I'm using ha-average for a sensor with unit of measurment V (voltage)

**Comment by arboeh** [comment]
Yep, can confirm this warning.

**Comment by Destroyer061090** [comment]
i have the same issues... how shoud i fix it?
here my actual code
```
- platform: average
  name: "sensor_name"
  duration:
    minutes: 15
  entities:
    - sensor.myentities_power
```

**Comment by Adrian57** [comment]
Same here.

**Comment by robvanoostenrijk** [comment]
Created a pull request with the necessary changes to resolve the warnings.

**Comment by Rudinskas** [comment]
I have the same warning.

**Comment by maia** [comment]
I would appreciate a review and merge of pull #218 . @Limych could you please take care of the PR? Thanks!

**Comment by omayhemo** [comment]
Average sensor is not averaging anymore, I believe to have been a problem since a late 2023 release.
