### ISSUE TITLE
STATE_CLASS_MEASUREMENT is a deprecated

### ISSUE THREAD

**Issue by Trzinka** [Limych/ha-average#226]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

`STATE_CLASS_MEASUREMENT` was used from average, this is a deprecated constant which will be removed in HA Core 2025.1. 
Use `SensorStateClass.MEASUREMENT` **instead**!

### Describe the solution you'd like

Use `SensorStateClass.MEASUREMENT` **instead**!

### Describe alternatives you've considered

?

### Additional context

?

**Comment by Limych** [comment]
#214
