### ISSUE TITLE
custom integration 'average' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 

### ISSUE THREAD

**Issue by wiedwo** [Limych/ha-average#237]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'average' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/average/sensor.py, line 246: async_track_state_change(, please create a bug report at https://github.com/Limych/ha-average/issues

### Describe the solution you'd like

fix

### Describe alternatives you've considered

none

### Additional context

none

**Comment by Lokilicious** [comment]
@Limych is this fix already released, as i still see this log line
