### ISSUE TITLE
Log Error (Detected that custom integration 'average' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/average/sensor.py, line 246: async_track_state_change)

### ISSUE THREAD

**Issue by Lokilicious** [Limych/ha-average#244]
## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 5.10.0-13-amd64
arch | x86_64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 16
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 18 June 2024 at 07:58
-- | --
current_recorder_run | 26 June 2024 at 08:34
estimated_db_size | 1300.29 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [ ] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-average/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Log says: Detected that custom integration 'average' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/average/sensor.py, line 246: async_track_state_change

### Reproduction steps

1. Use ha-average and observer logs

### Debug logs

```text
Detected that custom integration 'average' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/average/sensor.py, line 246: async_track_state_change
```

**Comment by Limych** [comment]
Please, update your component.

#237

**Comment by Lokilicious** [comment]
@Limych I see this error still in 2.3.4
