### ISSUE TITLE
'async_track_state_change' will be removed in Home Assistant 2025.5

### ISSUE THREAD

**Issue by wiedwo** [Limych/ha-average#248]
### System Health details

none

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-average/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Detected that custom integration 'average' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/average/sensor.py, line 246: async_track_state_change(, please create a bug report at https://github.com/Limych/ha-average/issues

### Reproduction steps

none

### Debug logs

```text
none
```

### Diagnostics dump

none

**Comment by Limych** [comment]
Already fixed at a19adc00eca6878974e4e17ec807aac1c967c5cf
