### ISSUE TITLE
Discard/ignore unrealistic sensor values

### ISSUE THREAD

**Issue by erikgeurts** [Limych/ha-average#254]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/Limych/ha-average/issues?q=is%3Aissue+label%3A%22enhancement%22+).

### Is your feature request related to a problem? Please describe.

Trying to average a sensor that sometimes returns unrealistic values, for example a grid voltage sensor that infrequently returns 0 volt or a negative value.

### Describe the solution you'd like

I'd like to be able to discard such values from the average calculation.

### Describe alternatives you've considered

I've considered first making a template sensor that discards values that I find to be unrealistic, and then to feed this template sensor to this average feature, but it would be very convenient to be able to skip this step, to avoid load on the system.

### Additional context

It could work in a way that's similar to how undefined values are discarded.

**Comment by Limych** [comment]
This sensor is exclusively engaged in calculating average values. Any data filtering is not included in its functions. If you need any additional preliminary data processing, please use other components. The result of which can be fed to the input of this sensor.
