### ISSUE TITLE
End attribute not working properly

### ISSUE THREAD

**Issue by robinostlund** [Limych/ha-average#257]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.8.0-47-generic
arch | x86_64
timezone | Europe/Stockholm
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1463
Downloaded Repositories | 40

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 16, 2025 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-0.ui.nabu.casa
certificate_status | ready
instance_id | c92eb76fef5e4836a4404e898751422a
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 14
-- | --
resources | 15
views | 73
mode | storage

</details>

<details><summary>MercedesME 2020</summary>

api_endpoint_reachable | ok
-- | --
websocket_connection_state | connected
cars_connected | 1
version | v0.19.0

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 6, 2024 at 08:01
-- | --
current_recorder_run | November 5, 2024 at 11:27
estimated_db_size | 27641.97 MiB
database_engine | mysql
database_version | 11.1.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Swedish Mail Delivery</summary>

Version | 1.0.7
-- | --
Idle | false
Instances | 1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-average/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

I have this sensor:
```
  - platform: average
    name: Ellevio Effect Fee Hourly Power Peak Average Sample
    entities:
      - sensor.ellevio_effect_fee_current_power_usage
    start: "{{ now().replace(minute=0, second=0, microsecond=0) }}"
    end: "{{ now().replace(minute=59, second=59, microsecond=999) }}"
```

But when checking the attributes of the sensor it shows this:
```
Start: November 5, 2024 at 11:00:00
End: November 5, 2024 at 11:35:27
```

Shouldn't end be November 5, 2024 at 11:59:59 ?

What i am trying to achieve is a average power sensor (in watts) during one hour.

Thanks

### Reproduction steps

Try my sensor

### Debug logs

```text
..
```

**Comment by Limych** [comment]
Senor can't calculate in the future.

If the end attribute is evaluated and is in the future, the value of this attribute is set to the current time.
