### ISSUE TITLE
Entity is renamed after every restart of HA

### ISSUE THREAD

**Issue by ruzickav** [Limych/ha-average#33]
Version of the Home Assistant: core-2021.3.1
Version of the custom component: v1.7.1

**Configuration**
```  - platform: average
    name: 'Temperature Last 3 Day Average'
    duration:
      days: 3
    entities:
      - sensor.temperaturelightcourtyard_am2301_temperature
```

Bug
After restart / reboot of Home assistant the entity of Average sensor becomes unavailable. New entity is created with _1 , _2 , _3 and so on - see attached screenshot
![entity](https://user-images.githubusercontent.com/58104955/110150646-c74fb200-7ddf-11eb-8d58-848a40d8b325.jpg)

LOG
```
2021-03-05 18:18:03 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.average
2021-03-05 18:18:03 INFO (MainThread) [custom_components.average.sensor]
-------------------------------------------------------------------
Average Sensor
Version: 1.7.1
This is a custom integration!
If you have ANY issues with this you need to open an issue here:
https://github.com/Limych/ha-average/issues
-------------------------------------------------------------------

2021-03-05 18:18:03 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.average entity: sensor.temperature_last_3_day_average_4
```

**Comment by LoneWolf345** [comment]
I'd confirm I'm seeing the same thing.

**Comment by Limych** [comment]
Sorry for that, guys...

**Comment by Limych** [comment]
To avoid such errors, I recently added unit tests to this component. The code is now only 54% covered by tests. There is still a lot of work to be done, but there is now a special check for this error.

**Comment by Gavin-A92** [comment]
Hi @Limych...just updated to latest version and this error remains

![image](https://user-images.githubusercontent.com/32313094/110159905-34187b80-7de3-11eb-9500-853ecaf51362.png)

**Comment by LoneWolf345** [comment]
It is now working again for me.  However, I did have to remove the duplicated entries. @Gavin-A92, maybe that is what you are seeing.

**Comment by Limych** [comment]
Since version 1.7.1 sensors have a unique ID. But in this version there was a bug that these IDs were new every time. This bug has been fixed in version 1.7.2. But if a version with a bug was previously launched, the sensors in the HA database have already been saved under incorrect IDs and, yes, the system will create new sensors. But this will only happen on the first launch.

Then you will have to, alas, manually delete duplicates and rename the sensors back. As a result for my HA, normal operation of the sensors and even their entire history was restored.

**Comment by DavidFW1960** [comment]
Well that was a nasty bug lol!

**Comment by Limych** [comment]
From now on I promise to release beta versions first.

**Comment by Gavin-A92** [comment]
> Since version 1.7.1 sensors have a unique ID. But in this version there was a bug that these IDs were new every time. This bug has been fixed in version 1.7.2. But if a version with a bug was previously launched, the sensors in the HA database have already been saved under incorrect IDs and, yes, the system will create new sensors. But this will only happen on the first launch.
> 
> Then you will have to, alas, manually delete duplicates and rename the sensors back. As a result for my HA, normal operation of the sensors and even their entire history was restored.

Yeah that's what had happened alright....I'd "cleaned" the extra entities and then rebooted to install 1.7.2 but exactly as you say they recreated......was too afraid to reboot again :-)
Have rebooted again this morning and all seems OK....thanks.......thanks to @LoneWolf345 too

**Comment by skynetforcats** [comment]
Man ... this is the most annoying bug ever 🤣😫🤣 I think I have well over 100 average sensors and I have a lot of them still in the "old" version.

**Comment by DavidFW1960** [comment]
If you go to config entities you should
Be able to filter and then check/delete all with 1 click
