### ISSUE TITLE
Error of HACS incompatibility 

### ISSUE THREAD

**Issue by dlo747** [Limych/ha-average#45]
**Environment**

- Home Assistant Core release with the issue: 2021.4.4

- This custom component release with the issue: 1.7.3

- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Home Assistant NUC

**Describe the bug**
``` Logger: homeassistant.loader
Source: loader.py:783 
First occurred: 11:51:26 PM (1 occurrences) 
Last logged: 11:51:26 PM

You are using a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**

Tried to remove repository and reinstall numerous times

**Expected behavior**

HACS supported integration 

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by Limych** [comment]
I do not understand. What's the bug?

**Comment by dlo747** [comment]
Source: loader.py:783 
First occurred: 11:51:26 PM (1 occurrences) 
Last logged: 11:51:26 PM

You are using a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

any way to get rid of that?

**Comment by Limych** [comment]
It's not a bug. It's common message Home Assistant post for any custom component.
And it's just warning message.

No, there are no way to get rid of that message.
