### ISSUE TITLE
The average integration is not logged as a statatistics

### ISSUE THREAD

**Issue by rabbadab** [Limych/ha-average#82]
Thank you for this great plugin! 
I saw the new statistics Lovelace card is expecting that the entity is listed as statistics and right now it feels the average is not doing this right now? 
https://www.home-assistant.io/more-info/statistics/

**Comment by skynetforcats** [comment]
Hmm I can't find any activity from @Limych since July 17th . Wonder if they are still around.

**Comment by Limych** [comment]
Added at 56ec08b3707cfa2731d02b860db9f09ffab5bc47
