### ISSUE TITLE
Add a 'median' calculation

### ISSUE THREAD

**Issue by Automan69** [Limych/ha-average#9]
Hi Limych, is it possible for you to add a 'median' calculation to this integration?

**Comment by Limych** [comment]
The calculation of the median requires storing in memory all variants of the values.  And this can very negatively affect the work of HA.  I will try to come up with something, but I doubt that it will work out.

**Comment by Limych** [comment]
There was a problem with the calculations.

Using the median formula, I want a complete list of all values. But this sensor, in fact, operates not with individual values, but with areas (with a geometric figure of complex shape). I have not yet been able to figure out how to calculate the median here…

**Comment by Automan69** [comment]
Hi Limych,

Thanks for the reply.  The work around I found was to use esphome.  It has a median filter on the sensor component.  I’ve now decided though to use better sensors that removes the need for filtering.

Cheers,

**Comment by Limych** [comment]
Nice. Then I close this issue as no longer relevant.
